export const mainTheme = {
    dark: false,
    colors: {
      background: '#FFFFFF',
      surface: '#FFFFFF',
      'surface-bright': '#FFFFFF',
      'surface-light': '#EEEEEE',
      'surface-variant': '#424242',
      'on-surface-variant': '#EEEEEE',
      primary: '#1867C0',
      'primary-darken-1': '#1F5592',
      secondary: '#48A9A6',
      'secondary-darken-1': '#018786',
      error: '#B00020',
      info: '#2196F3',
      success: '#4CAF50',
      warning: '#FB8C00',
      'appbar':"#B00020",
      'drawerbar':"#fff",
      'brandcolor':"",
      'defaulticonColor':"#e9943e",
      'rscolor':'#1abc9c',
      'sellcolor':'#16a34a',
      'dailogbarcolor':'#B00020',
      'searchbtn':'#4CAF50',
      'printbillbtn':'#2196F3',
      'paymentbtn':'#16a34a',
      'paymentbtnhover':'#0d602b',
      'submitorder':'#2563eb',
      'submitorderhover':'#1D4ED8',
      'saletable':'#ECFEFF',
      'border-text': '#fff',
      'totaldiscount': '#FB8C00',
      'grandtotalbtn':'#4CAF50',
      'textaction':'#2563EB'
    },
    variables: {
      'border-color': '#000000',
      'border-opacity': 0.12,
      'high-emphasis-opacity': 0.87,
      'medium-emphasis-opacity': 0.60,
      'disabled-opacity': 0.38,
      'idle-opacity': 0.04,
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'theme-kbd': '#212529',
      'theme-on-kbd': '#FFFFFF',
      'theme-code': '#F5F5F5',
      'theme-on-code': '#000000',
      
      
    }
  }
  
  export const secondaryTheme = {
	dark: false,
	colors: {
	  background: '#eff2f7',
	  surface: '#FFFFFF',
	  'surface-bright': '#FFFFFF',
	  'surface-light': '#EEEEEE',
	  'surface-variant': '#424242',
	  'on-surface-variant': '#EEEEEE',
	  primary: '#1abc9c',
    info:'#1abc9c',
	  'primary-darken-1': '#1F5592',
	  secondary: '#1abc9c',
	  'secondary-darken-1': '#018786',
	  error: '#B00020',
	  success: '#4CAF50',
	  warning: '#FB8C00',
    'appbar':"#1abc9c",
    'drawerbar':"#1abc9c",
    'brandcolor':"#1abc9c",
    'defaulticonColor':"#FFFFFF",
    'rscolor':'#1abc9c',
    'sellcolor':'#1abc9c',
    'dailogbarcolor':'#1abc9c',
    'searchbtn':'#1abc9c',
    'printbillbtn':'#1abc9c',
    'paymentbtn':'#1abc9c',
    'paymentbtnhover':'#148f77',
    'submitorder':'#14888f',
    'submitorderhover':'#148f77',
    'saletable':'#1abc9c',
    'border-text': '#fff',
    'totaldiscount': '#1abc9c',
    'grandtotalbtn':'#1abc9c',
    'textaction':'#1abc9c'
	},
	variables: {
	  'border-color': '#000000',
	  'border-opacity': 0.12,
	  'high-emphasis-opacity': 0.87,
	  'medium-emphasis-opacity': 0.60,
	  'disabled-opacity': 0.38,
	  'idle-opacity': 0.04,
	  'hover-opacity': 0.04,
	  'focus-opacity': 0.12,
	  'selected-opacity': 0.08,
	  'activated-opacity': 0.12,
	  'pressed-opacity': 0.12,
	  'dragged-opacity': 0.08,
	  'theme-kbd': '#212529',
	  'theme-on-kbd': '#FFFFFF',
	  'theme-code': '#F5F5F5',
	  'theme-on-code': '#000000',
	}
  }
